In [5]:

print("hello world")

hello world

In [9]:
import os
from dotenv import load_dotenv
from kaggle.api.kaggle_api_extended import KaggleApi

load_dotenv()

os.environ['KAGGLE_USERNAME'] = "sanyamgupta12"
os.environ['KAGGLE_KEY'] = os.getenv("API_TOKEN")

api = KaggleApi()
api.authenticate()

api.dataset_download_files('najir0123/walmart-10k-sales-datasets', path='./data', unzip=True)

Dataset URL: https://www.kaggle.com/datasets/najir0123/walmart-10k-sales-datasets

# **STEP 1: Data Exploration & Loading**

In [34]:
import pandas as pd

# mysql toolkit
import pymysql                           #works as adapter
from sqlalchemy import create_engine

In [15]:
print(pd.__version__)

3.0.2

In [16]:
df = pd.read_csv('./data/Walmart.csv', encoding_errors='ignore')

df.shape

(10051, 11)

In [17]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [18]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [20]:
# all duplicates
df.duplicated().sum()

np.int64(51)

In [21]:
df.drop_duplicates(inplace=True)
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [22]:
df.shape

(10000, 11)

In [23]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [24]:
# dropping all rows with missing values
df.dropna(inplace=True)

In [25]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [26]:
df.shape

(9969, 11)

In [27]:
df.dtypes

invoice_id          int64
Branch                str
City                  str
category              str
unit_price            str
quantity          float64
date                  str
time                  str
payment_method        str
rating            float64
profit_margin     float64
dtype: object

In [28]:
df['unit_price'].astype(float)

ValueError: could not convert string to float: '$74.69'

In [29]:
df['unit_price'] = df['unit_price'].str.replace('$','').astype(float)

In [30]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [31]:
df.info()

<class 'pandas.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   str
 2   City            9969 non-null   str
 3   category        9969 non-null   str
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   str
 7   time            9969 non-null   str
 8   payment_method  9969 non-null   str
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), str(6)
memory usage: 934.6 KB

In [32]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='str')

In [33]:
df['total'] = df['unit_price'] * df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [ ]:
# import os
# from dotenv import load_dotenv
# load_dotenv()
# mysql
#
# host = localhost
# port = 3306
# user = root
# password = os.getenv("MYSQL_PASSWORD")

In [35]:
df.shape

(9969, 12)

In [36]:
df.to_csv('./data/Walmart.csv', index=False)

In [54]:
import os
import urllib.parse
from dotenv import load_dotenv
from sqlalchemy import create_engine, text # Added imports

load_dotenv()

# 1. Get and encode password to handle special characters (@, #, !, etc.)
raw_password = os.getenv("MYSQL_PASSWORD")
password = urllib.parse.quote_plus(raw_password) if raw_password else ""

string_val = f"mysql+pymysql://root:{password}@localhost:3306/walmart_db"

# 2. Create the engine
engine_mysql = create_engine(string_val)

# 3. Actually test the connection
try:
    with engine_mysql.connect() as connection:
        # We run a tiny query to verify the connection is alive
        connection.execute(text("SELECT 1"))
    print("Connection Successful to MySQL!")
except Exception as e:
    print(f"Unable to connect: {e}")

Connection Successful to MySQL!

In [55]:
df.to_sql(name="walmart", con=engine_mysql, if_exists='append', index=False)

9969